### ISSUE TITLE
tab组件第一次进去没有默认选中

### ISSUE THREAD

**Issue by Liqiankun** [dyq086/wxYuHanStore#1]
![2017-12-05 3 14 05](https://user-images.githubusercontent.com/11532418/33594484-a09170c8-d959-11e7-9366-19f03993bdce.png)

**Comment by dyq086** [comment]
这份代码比较旧了，我上传了最新，应该可以解决你的问题

**Comment by Liqiankun** [comment]
@dyq086 好我来试试！

**Comment by Liqiankun** [comment]
```
currentTab: 0
```
page页面写成这样解决了这个问题
