### ISSUE TITLE
请问你开发的编辑器有语法提示么？

### ISSUE THREAD

**Issue by fantasy525** [dyq086/wxYuHanStore#12]
目前都是配置语法高亮的，但是如何配置语法自动提示呢

**Comment by dyq086** [comment]
这个没有提示的哈，敲多了就熟练了

**Comment by fantasy525** [comment]
好的，感谢回复，如果有时间，我想向大神咨询个问题
```javascript
 wx.getSetting({
      success: res => {
        if (res.authSetting['scope.userInfo']) {
          console.log('已经授权')
          // 已经授权，
          wx.getUserInfo({
            success: res => {
              console.log('app.js执行 getUserInfo')
              // 可以将 res 发送给后台解码出 unionId
              this.globalData.userInfo = res.userInfo

              // 由于 getUserInfo 是网络请求，可能会在 Page.onLoad 之后才返回
              // 所以此处加入 callback 以防止这种情况
              if (this.userInfoReadyCallback) {
                this.userInfoReadyCallback(res)
              }
            }
          })
        }else{ // 没有授权过
          wx.getUserInfo({
            success: res => {
              console.log('app.js执行 getUserInfo2')
              // 可以将 res 发送给后台解码出 unionId
              this.globalData.userInfo = res.userInfo

              // 由于 getUserInfo 是网络请求，可能会在 Page.onLoad 之后才返回
              // 所以此处加入 callback 以防止这种情况
              if (this.userInfoReadyCallback) {
                this.userInfoReadyCallback(res)
              }
            }
          })
        }
      }
    })


```
> 上面的代码是用微信开发工具是初始化的demo，自动在app.js生成的基础上加了代码生成的
## 问题
+  我第一次运行小程序时代码会走else分支，然后弹窗提示请求授权，然后点击同意后，我重新编译小程序，当程序运行时小程序会走if分支，同样也会执行``` wx.getUserInfo() ```,但是为什么没有弹窗呢？
+ 上述也就是区分在一个授权了一个没有授权，但是仅仅是if else 的分支不同，都调用了wx.getUserInfo，为什么if 里面没有弹窗呢？

**Comment by dyq086** [comment]
授权情况只针对第一次，对于已经授权是不会再次弹窗的，若用户拒绝授权必须删除小程序重新进入才会再次调起弹窗，开发的时候再次弹窗只能在开发者工具里边去清除授权信息
![image](https://user-images.githubusercontent.com/19547692/35470117-966285de-037e-11e8-84d4-a432318218c9.png)

**Comment by fantasy525** [comment]
好的，感谢回复

**Comment by fantasy525** [comment]
大神，还要个问题，我在开发自定义组件时，不是很理解文档中提到的

![tim 20180128211236](https://user-images.githubusercontent.com/22516157/35482434-ff9d0762-046f-11e8-9550-3532bd17b629.png)
+ 关于这三个修饰符，我目前只知道如果加了user,就需要把方法写在methods中，然后我不用user就需要写在events中，我不是很明白什么时候需要写在events或者methods中，
+ 还有.default修饰符，我不理解文档说的用来绑定小程序冒泡事件？用@给组件绑定的事件不都是自定义事件么？如何用这个呢？是@tap=“”，然后子组件里面$emit('tap')?

**Comment by dyq086** [comment]
你可以理解为
$broatcase和$emit的相关事件写在events 里
@tap, @input, @userFn.user 这一类事件写在methods 里
.default默认是绑定原生事件,事件的触发顺序自内向外，这就是冒泡型事件。利用@tap.stop="xxx"就可以阻止/捕获事件冒泡，组件必须要用自定义事件不能用原生事件

**Comment by fantasy525** [comment]
感谢回复，但是我还是有几个疑问：
还是拿例子来问吧
```javascript
// index.wpy

<template>
    <child @childFn.user="parentFn"></child>// 绑定自定义事件名称
    <child @childFn="parentFn"></child>//此时默认绑定小程序冒泡型事件，那我该在哪里触发这个冒泡型事件呢？如果这样写下面父组件events和methods是否需要修改什么呢(改变方法写的位置？)
</template>

<script>
    import wepy from 'wepy'
    import Child from '../components/child'

    export default class Index extends wepy.page {
        components = {
            child: Child
        }

        methods = {
            parentFn (num, evt) {
                console.log('parent received emit event, number is: ' + num)
            }
        }
    }
</script>


// child.wpy

<template>
    <view @tap="tap">Click me</view>
</template>

<script>
    import wepy from 'wepy'

    export default class Child extends wepy.component {
        methods = {
            tap () {
                console.log('child is clicked')
                this.$emit('childFn', 100)// 子组件通过$emit()触发父组件.user修饰符绑定的methods中方法
            }
        }
    }
</script>
```
+ 您看一下我上面注释有没有错误，另外我想看一下怎么触发@childFn="parentFn"也就是默认小程序原生事件。可以写个用法让我看看

**Comment by dyq086** [comment]
建议你多看一下文档，理解什么是原生事件，什么是自定义组件事件哈

**Comment by fantasy525** [comment]
大神，按照您的建议，刚看了一会，现在理解你原生事件和自定义组件事件，仍然有最后一个疑问，按照这句话理解，
> @tap, @input, @userFn.user 这一类事件写在methods 里

那么是不是要用emit去触发这个自定义userFn事件呢？如果是，那你在开头又说

> 你可以理解为$broatcase和$emit的相关事件写在events 里

这个是不是矛盾了？
#### 下面我自己测试了下发现是不矛盾的，但是不确定理解的对不对
+ 先 确认下为wepy中自定义的事件应该都是用emit触发吧？我觉得是！
+ 如果用``` @childFn.user="xxx"``` 的话那触发的事件对应的方法是写在methods中，如果不用，那这个方法可以写在events对象中，key为emit中的事件名，value为对应的事件处理方法，那么，在这个前提下，methods中的方法会覆盖events中的方法，对应了官方文档说的 
> #### 注意，如果用了自定义事件，则events中对应的监听函数不会再执行。
+综上理解，好像是子组件emit的事件写在events和methods中都能达到同样的效果啊？ 那我怎么决定何时把事件写在events中呢还是在标签上写上@childFn.user="xxx"，然后methods中写方法，
