### ISSUE TITLE
你的后端用的是什么程序呢？

### ISSUE THREAD

**Issue by shaohao2014** [dyq086/wxYuHanStore#19]
你的后端用的是什么程序呢？是自行开发的？还是用的免费开源的后端？还是付费的后台呢？能否推荐一下？谢谢

**Comment by huanhuanuncle** [comment]
Java ，自己开发的

**Comment by dyq086** [comment]
开发语言：JAVA 基于Maven的Spring+SpringMVC+Mybatis 
数据库：Mysql
