### ISSUE TITLE
Error: 缺少文件, error: /app.json not found

### ISSUE THREAD

**Issue by wangqianjun** [dyq086/wxYuHanStore#25]
运行过 `npm run build` 后在微信开发者工具 里面点击预览报错

![image](https://user-images.githubusercontent.com/8085482/39223553-5374ca84-4875-11e8-8470-8ee84e2fb651.png)

**Comment by lcyh** [comment]
我也遇到  app.json未找到,请问怎么解决的

**Comment by dyq086** [comment]
开发使用说明(重要)
1、使用微信开发者工具-->添加项目，项目目录请选择dist目录。

2、微信开发者工具-->项目-->关闭ES6转ES5。 重要：漏掉此项会运行报错。

3、微信开发者工具-->项目-->关闭上传代码时样式自动补全。 重要：某些情况下漏掉此项也会运行报错。

4、微信开发者工具-->项目-->关闭代码压缩上传。 重要：开启后，会导致真机computed, props.sync 等等属性失效。
